export const SORT_OPTIONS = [
  { value: "recent", label: "Plus récents" },
  { value: "price-asc", label: "Prix croissant" },
  { value: "price-desc", label: "Prix décroissant" },
  { value: "rating", label: "Mieux notés" },
];

export const CATEGORY_RULES = [
  {
    slug: "electronique",
    name: "Électronique",
    description: "Tech, smartphones, ordinateurs et accessoires.",
    keywords: [
      "tech",
      "technologie",
      "electronique",
      "electromenager",
      "smartphone",
      "telephone",
      "iphone",
      "samsung",
      "ordinateur",
      "computer",
      "laptop",
      "pc",
      "gaming",
      "console",
      "playstation",
      "ps5",
      "casque",
      "ecouteur",
      "chargeur",
      "camera",
      "ecran",
      "televiseur",
      "tv",
      "ssd",
      "hdd",
    ],
    negativeKeywords: [
      "biscuit",
      "gel douche",
      "parfum",
      "montre",
      "savon",
      "riz",
      "spaghetti",
    ],
  },
  {
    slug: "mode",
    name: "Mode & Luxe",
    description: "Vêtements, chaussures, montres, sacs et accessoires.",
    keywords: [
      "mode",
      "fashion",
      "luxe",
      "vetement",
      "veste",
      "chaussure",
      "basket",
      "sneaker",
      "sac",
      "sac a main",
      "bijou",
      "montre",
      "emporio",
      "armani",
      "rolex",
      "textile",
      "habit",
      "robe",
      "chemise",
      "shirt",
      "pantalon",
      "jean",
    ],
    negativeKeywords: [
      "sachet",
      "biscuit",
      "biscuits",
      "riz",
      "farine",
      "spaghetti",
      "pates",
      "savon",
      "gel douche",
      "shampoing",
      "fer a repasser",
    ],
  },
  {
    slug: "maison",
    name: "Maison & Design",
    description: "Décoration, mobilier, cuisine, maison et électroménager.",
    keywords: [
      "maison",
      "home",
      "design",
      "deco",
      "decoration",
      "meuble",
      "mobilier",
      "jardin",
      "interieur",
      "cuisine",
      "mixeur",
      "blender",
      "fer a repasser",
      "repasser",
      "aspirateur",
      "ventilateur",
      "climatiseur",
      "refrigerateur",
      "micro onde",
      "four",
      "vaisselle",
      "casserole",
    ],
    negativeKeywords: [
      "biscuit",
      "biscuits",
      "riz",
      "spaghetti",
      "farine",
      "parfum",
      "montre",
      "gel douche",
    ],
  },
  {
    slug: "beaute",
    name: "Beauté & Bien-être",
    description: "Cosmétiques, soins, parfums, hygiène et bien-être.",
    keywords: [
      "beaute",
      "beauty",
      "cosmetique",
      "soin",
      "soins",
      "parfum",
      "eau de parfum",
      "sauvage",
      "boss",
      "hugo boss",
      "gel douche",
      "douche",
      "cadum",
      "savon",
      "shampoing",
      "shampoo",
      "creme",
      "lotion",
      "deodorant",
      "hygiene",
      "cheveux",
      "skin",
      "visage",
      "wellness",
      "bien etre",
    ],
    negativeKeywords: [
      "biscuit",
      "biscuits",
      "riz",
      "spaghetti",
      "montre",
      "fer a repasser",
      "mixeur",
    ],
  },
  {
    slug: "alimentation",
    name: "Alimentation",
    description: "Épicerie, boissons, snacks et produits alimentaires.",
    keywords: [
      "food",
      "alimentaire",
      "alimentation",
      "epicerie",
      "boisson",
      "jus",
      "eau",
      "snack",
      "patisserie",
      "repas",
      "biscuit",
      "biscuits",
      "sachet",
      "riz",
      "farine",
      "sucre",
      "sel",
      "huile",
      "lait",
      "cafe",
      "the",
      "tomate",
      "spaghetti",
      "pates",
      "pate",
      "conserve",
      "bonbon",
      "chocolat",
      "cereales",
    ],
    negativeKeywords: [
      "fer a repasser",
      "mixeur",
      "blender",
      "montre",
      "emporio",
      "armani",
      "parfum",
      "sauvage",
      "boss",
      "gel douche",
      "cadum",
      "savon",
      "shampoing",
      "telephone",
      "ordinateur",
    ],
  },
  {
    slug: "artisanat",
    name: "Artisanat",
    description: "Créations locales, fait main et produits artisanaux.",
    keywords: [
      "artisan",
      "artisanat",
      "handmade",
      "fait main",
      "local",
      "creation",
      "atelier",
      "traditionnel",
    ],
    negativeKeywords: [],
  },
  {
    slug: "autres",
    name: "Autres",
    description: "Produits divers non classés dans les catégories principales.",
    keywords: [],
    negativeKeywords: [],
  },
];

export const CATEGORY_PRODUCTS_PER_PAGE = 8;
