/** RefEntityId fallbacks used by ApiImage for product cards. */

export function getProductRefEntityIdCandidates(product, productId) {
  return [
    productId,
    product?.id,
    product?.productId,
    product?.refId,
    product?.summaryId,
    product?.promoId,
    product?.userPreferenceSummaryDto?.refId,
    product?._raw?.id,
    product?._raw?.productId,
    product?._raw?.refId,
    product?._raw?.summaryId,
    product?._raw?.promoId,
    product?._raw?.userPreferenceSummaryDto?.refId,
    product?.productPromoSummaryDto?.id,
    product?.productPromoSummaryDto?.productId,
    product?.productPromoHeaderSummaryDto?.id,
    product?.productPromoHeaderSummaryDto?.productId,
    product?.clientCatalogProductSummaryDto?.id,
    product?.clientCatalogProductSummaryDto?.productId,
    product?.catalogProductSummaryDto?.id,
    product?.catalogProductSummaryDto?.productId,
    product?.productHeaderSummaryDto?.id,
    product?.productHeaderSummaryDto?.productId,
    product?._raw?.productPromoSummaryDto?.id,
    product?._raw?.productPromoSummaryDto?.productId,
    product?._raw?.productPromoHeaderSummaryDto?.id,
    product?._raw?.productPromoHeaderSummaryDto?.productId,
    product?._raw?.clientCatalogProductSummaryDto?.id,
    product?._raw?.clientCatalogProductSummaryDto?.productId,
    product?._raw?.catalogProductSummaryDto?.id,
    product?._raw?.catalogProductSummaryDto?.productId,
    product?._raw?.productHeaderSummaryDto?.id,
    product?._raw?.productHeaderSummaryDto?.productId,
  ].filter(Boolean);
}
